name = "PNGFiles"
uuid = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"
authors = ["Ian Butterworth", "Tomáš Drvoštěp"]
version = "0.1.2"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
libpng_jll = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"

[compat]
CEnum = "0.2"
julia = "1.3"
libpng_jll = "1.6.37"

[extras]
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["Glob", "Images", "ImageMagick", "Logging", "Random", "Tar", "Test", "TestImages"]
