name = "PNG"
uuid = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"
authors = ["Ian Butterworth"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
libpng_jll = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"

[compat]
CEnum = "^0.2"
ColorTypes = "^0.9"
FileIO = "^1.2"
FixedPointNumbers = "^0.7"
ImageCore = "^0.8"
julia = "^1.3"
libpng_jll = "1.6.37"

[extras]
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["Glob", "ImageMagick", "Logging", "Random", "Test", "TestImages"]
